name: 'Swift Hybrid Analyzer'
description: 'Гібридний аналіз Swift-коду (AST + LLM)'
inputs:
  file-path:
    description: 'Шлях до файлу для аналізу'
    required: true
  api-key:
    description: 'API ключ для LLM'
    required: true
  output-path:
    description: 'Шлях для збереження звіту'
    required: false
    default: 'report.json'
runs:
  using: 'composite'
  steps:
    - name: 'Run Analyzer'
      shell: bash
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Це прибере твоє попередження про Node.js
      run: |
        # Переходимо в папку самого екшена, де лежить Package.swift
        cd "${{ github.action_path }}/Analyzer"
        
        # Запускаємо аналізатор, вказуючи повний шлях до файлу в проєкті
        swift run Analyzer "${{ github.workspace }}/${{ inputs.file-path }}" \
          --api-key "${{ inputs.api-key }}" \
          --output "${{ github.workspace }}/${{ inputs.output-path }}"
